### ISSUE TITLE
Problem with processing data containing quotation marks - unhandled `error` event ()

### ISSUE THREAD

**Issue by gustawdaniel** [pstaender/csv2md#1]
System

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Node Js

```
$ nodejs -v
v4.2.6
```

Npm

```
$ npm -v
3.5.2
```

Method of installation your package:

```
$ sudo npm install -g csv2md
/usr/local/bin/csv2md -> /usr/local/lib/node_modules/csv2md/bin/csv2md
/usr/local/lib
└── csv2md@0.0.6 
```

My file: `access.csv`

```
$ cat access.csv
id,client_id,token_type,access_token,expires_in,scope
1,1,Bearer,A1,NULL,["test"]
2,2,Bearer,B2,NULL,["test"]
3,3,Bearer,C3,NULL,["test"]
4,4,Bearer,D4,NULL,["test"]
5,5,Bearer,E5,NULL,["test"]
6,6,Bearer,F6,NULL,["test"]
7,7,Bearer,G7,NULL,["test"]
```

Effect of usage your soft on this file:

```
$ csv2md access.csv
| id | client_id | token_type | access_token | expires_in | scope |
|---|---|---|---|---|---|
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Invalid opening quote at line 2
    at Parser.__write (/usr/local/lib/node_modules/csv2md/node_modules/csv-parse/lib/index.js:261:15)
    at Parser._transform (/usr/local/lib/node_modules/csv2md/node_modules/csv-parse/lib/index.js:138:10)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Writable.write (_stream_writable.js:207:11)
    at ReadStream.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at ReadStream.emit (events.js:169:7)
```

I hope these infos allow to reproduce bug and It will be helpful. Anyway I congratulate idea of create software converting csv to markdown. It is very needed and useful.

**Comment by gustawdaniel** [comment]
I found workaround...

```
$ cat access.csv | tr "\"" "_" | csv2md | tr "_" "\""
| id | client"id | token"type | access"token | expires"in | scope |
|---|---|---|---|---|---|
| 1 | 1 | Bearer | A1 | NULL | ["test"] |
| 2 | 2 | Bearer | B2 | NULL | ["test"] |
| 3 | 3 | Bearer | C3 | NULL | ["test"] |
| 4 | 4 | Bearer | D4 | NULL | ["test"] |
| 5 | 5 | Bearer | E5 | NULL | ["test"] |
| 6 | 6 | Bearer | F6 | NULL | ["test"] |
| 7 | 7 | Bearer | G7 | NULL | ["test"] |
```

But I hope you can fix this imperfection on level of your code. Have nice day!

**Comment by pstaender** [comment]
Hi, nice to hear that you have use cases for the software :)

The problem occurs while parsing the csv file with the csv parser (http://csv.adaltas.com/parse/). I think your csv is not valid. As Wikipedia says (sry, I didn't get through the RFC) in https://en.wikipedia.org/wiki/Comma-separated_values :

```
Fields with embedded commas or double-quote characters must be quoted.
1997,Ford,E350,"Super, luxurious truck"

Each of the embedded double-quote characters must be represented by a pair of double-quote characters.
1997,Ford,E350,"Super, ""luxurious"" truck"
```

So if your file is like:

```
id,client_id,token_type,access_token,expires_in,scope
1,1,Bearer,A1,NULL,"[""test""]"
2,2,Bearer,B2,NULL,"[""test""]"
```

the transformation works correctly without any errors:

``` sh
$ cat access.csv | csv2md       
| id | client_id | token_type | access_token | expires_in | scope |
|---|---|---|---|---|---|
| 1 | 1 | Bearer | A1 | NULL | ["test"] |
| 2 | 2 | Bearer | B2 | NULL | ["test"] |
```
